global using Avalonia.Controls;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Avalonia.Media.Immutable;
global using Avalonia.Platform;
global using Avalonia.VisualTree;
//global using CefNet;
global using Microsoft.Web.WebView2.Core;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.Runtime.ConstrainedExecution;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using AvaloniaColor = Avalonia.Media.Color;
global using Color = System.Drawing.Color;
